Repository invader237/FitPick-back, pull requests merged in 2024-12, with the labels that each got.

#6 🛡️ Authentication Module Implementation
  Dockerfile
  pom.xml
  src/main/java/com/example/project/config/Authentification/JwtAuthFilter.java
  src/main/java/com/example/project/config/Authentification/JwtUtil.java
  src/main/java/com/example/project/config/Authentification/PasswordEncoderConfig.java
  src/main/java/com/example/project/config/Authentification/SecurityConfig.java
  src/main/java/com/example/project/controller/Authentification/AuthController.java
  src/main/java/com/example/project/dto/Authentification/ChangePasswordDTO.java
  src/main/java/com/example/project/dto/Authentification/LoginRequestDTO.java
  src/main/java/com/example/project/dto/Authentification/LoginResponseDTO.java
  src/main/java/com/example/project/dto/Authentification/RegisterRequestDTO.java
  src/main/java/com/example/project/modele/Authentification/Role.java
  src/main/java/com/example/project/modele/Authentification/User.java
  src/main/java/com/example/project/repository/Authentification/RoleRepository.java
  src/main/java/com/example/project/repository/Authentification/UserRepository.java
  src/main/java/com/example/project/service/Authentification/AuthService.java
  src/main/resources/application.properties
  src/test/java/com/example/project/ProjectApplicationTests.java
  src/test/java/com/example/project/config/Authentification/JwtAuthFilterTest.java
  src/test/java/com/example/project/config/Authentification/JwtUtilTest.java
  src/test/java/com/example/project/config/Authentification/PasswordEncoderConfigTest.java
  src/test/java/com/example/project/config/Authentification/SecurtyConfigTest.java
  src/test/java/com/example/project/config/Authentification/WebConfigTest.java
  src/test/java/com/example/project/controlleur/Authentification/AuthControllerTest.java
  src/test/java/com/example/project/dto/Authentification/ChangePasswordDTOTest.java
  src/test/java/com/example/project/dto/Authentification/LoginRequestDTOTest.java
  src/test/java/com/example/project/dto/Authentification/LoginResponseDTOTest.java
  src/test/java/com/example/project/dto/Authentification/RegisterRequestDTOTest.java
  src/test/java/com/example/project/modele/Authentification/RoleTest.java
  src/test/java/com/example/project/modele/Authentification/UserTest.java
  src/test/java/com/example/project/repository/Authentification/RoleRepositoryTest.java
  src/test/java/com/example/project/repository/Authentification/UserRepositoryTest.java
  src/test/java/com/example/project/service/Authentification/AuthServiceTest.java
Labels: enhancement

#8 🔒 Bugfix: Fix endpoint authorization and rename for consistency
  src/main/java/com/example/project/config/Authentification/SecurityConfig.java
  src/main/java/com/example/project/controller/WeatherController.java
Labels: bug

#9 :construction_worker: (ci): Update linter workflow to run on all branches
  .github/workflows/backend.yml
Labels: bug

#10 🚀 Feature/cloth-lib: Add Clothing Library Backend Functionality
  pom.xml
  src/main/java/com/example/project/controller/clothingLib/ClothingLibController.java
  src/main/java/com/example/project/controller/clothingLib/TagController.java
  src/main/java/com/example/project/dto/clothingLib/ClothingDTO.java
  src/main/java/com/example/project/dto/clothingLib/ClothingRequest.java
  src/main/java/com/example/project/dto/clothingLib/TagDTO.java
  src/main/java/com/example/project/modele/clothingLib/Clothing.java
  src/main/java/com/example/project/modele/clothingLib/Tag.java
  src/main/java/com/example/project/repository/clothingLib/ClothingRepository.java
  src/main/java/com/example/project/repository/clothingLib/TagRepository.java
  src/main/java/com/example/project/service/clothingLib/ClothingService.java
  src/main/java/com/example/project/service/clothingLib/TagService.java
  src/main/resources/application.properties
  src/test/java/com/example/project/modele/clothingLib/ClothingTest.java
  src/test/java/com/example/project/modele/clothingLib/TagTest.java
  src/test/java/com/example/project/service/clothingLib/ClothingServiceTest.java
  src/test/java/com/example/project/service/clothingLib/TagServiceTest.java
Labels: bug, enhancement

#13 🐛 Fix: Temporary adjustments for authentication and project configuration
  pom.xml
  src/main/java/com/example/project/config/Authentification/SecurityConfig.java
  src/main/resources/application.properties
Labels: bug

#15 ✨ Add dedicated files for weather-related data
  src/main/java/com/example/project/controller/Weather/WeatherController.java
  src/main/java/com/example/project/model/Weather/WeatherDataDisplay.java
  src/main/java/com/example/project/model/Weather/WeatherResponse.java
  src/main/java/com/example/project/service/Weather/WeatherService.java
Labels: bug
