Repository invader237/FitPick-back, pull requests merged in 2025-01, with the labels that each got.

#16 # 🌟 Comprehensive Refactor: User Management, AWS S3 Integration, and Enhanced Clothing & Tag Services
  docker-compose.yml
  pom.xml
  src/main/java/com/example/project/config/Authentification/JwtAuthFilter.java
  src/main/java/com/example/project/config/Clothing/AwsConfig.java
  src/main/java/com/example/project/controller/clothingLib/ClothingLibController.java
  src/main/java/com/example/project/controller/clothingLib/TagController.java
  src/main/java/com/example/project/dto/clothingLib/ClothingDTO.java
  src/main/java/com/example/project/dto/clothingLib/ClothingRequest.java
  src/main/java/com/example/project/dto/clothingLib/TagDTO.java
  src/main/java/com/example/project/model/clothingLib/Clothing.java
  src/main/java/com/example/project/service/clothingLib/AwsS3Service.java
  src/main/java/com/example/project/service/clothingLib/ClothingService.java
  src/main/java/com/example/project/service/clothingLib/TagService.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/application.properties
Labels: enhancement

#17 🔐 Correctifs : Amélioration de la sécurité et de la configuration CORS dans WebConfig et SecurityConfig
  docker-compose.yml
  src/main/java/com/example/project/config/Authentification/SecurityConfig.java
  src/main/java/com/example/project/config/WebConfig.java
  src/main/resources/application.properties
Labels: bug

#19 Feature/outfit lib
  docker-compose.yml
  src/main/java/com/example/project/config/Authentification/SecurityConfig.java
  src/main/java/com/example/project/controller/outfitLib/OutfitLibController.java
  src/main/java/com/example/project/dto/outfitLib/OutfitDTO.java
  src/main/java/com/example/project/dto/outfitLib/OutfitDisplay.java
  src/main/java/com/example/project/dto/outfitLib/OutfitRequest.java
  src/main/java/com/example/project/model/outfitLib/Outfit.java
  src/main/java/com/example/project/repository/clothingLib/ClothingRepository.java
  src/main/java/com/example/project/repository/outfitLib/OutfitRepository.java
  src/main/java/com/example/project/service/outfitLib/OutfitService.java
Labels: bug, enhancement
